// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/customs": {
            "get": {
                "description": "전체고객 목록조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Custom"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Custom"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "고객등록",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Custom"
                ],
                "parameters": [
                    {
                        "description": "기본키 원랜입력안해야함",
                        "name": "id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "고객아이디 ex SAMSUNG",
                        "name": "eid",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "고객명 ex 삼성",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "우편번호10자이내",
                        "name": "postno",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "기본주소",
                        "name": "basadr",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "상세주소",
                        "name": "dtladr",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "사업자여부 1 or 0",
                        "name": "type",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "그라파나 회사 pk 입력안해야함원랜",
                        "name": "orgid",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    }
                }
            }
        },
        "/customs/{id}": {
            "get": {
                "description": "고객 id로 고객 단일조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Custom"
                ],
                "summary": "{id}고객아이디",
                "operationId": "get-string-by-int",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "고객아이디",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Custom"
                        }
                    }
                }
            }
        },
        "/equip": {
            "get": {
                "description": "influx 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equip"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "장치아이디",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "태그명",
                        "name": "tag",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Response"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "description": "전체사용자 목록조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Users"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.FailedMessage"
                        }
                    }
                }
            },
            "post": {
                "description": "사용자추가",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "parameters": [
                    {
                        "description": "사용자명",
                        "name": "name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "비밀번호",
                        "name": "pwd",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "연락처",
                        "name": "phone",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "email",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "1",
                        "name": "admin",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "13",
                        "name": "custID",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "2",
                        "name": "gfId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "부서",
                        "name": "dept",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "직급",
                        "name": "position",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "비고",
                        "name": "rec",
                        "in": "body",
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Message"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.FailedMessage"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "사용자 id로 사용자 단일조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "{id} 사용자아이디",
                "operationId": "get-string-by-int",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "사용자아이디",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Users"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.FailedMessage"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.Influx": {
            "type": "object",
            "properties": {
                "t": {
                    "type": "string"
                },
                "v": {
                    "type": "string"
                }
            }
        },
        "controller.Response": {
            "type": "object",
            "properties": {
                "i": {
                    "type": "string"
                },
                "k": {
                    "type": "string"
                },
                "value": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controller.Influx"
                    }
                }
            }
        },
        "models.Custom": {
            "type": "object",
            "properties": {
                "appryn": {
                    "type": "string",
                    "example": "Y"
                },
                "basadr": {
                    "type": "string",
                    "example": "서울특별시 강서구 화곡로 12"
                },
                "compno": {
                    "type": "string",
                    "example": "17282718127"
                },
                "createdat": {
                    "type": "string",
                    "example": "2020-01-29 13:10:39"
                },
                "dtladr": {
                    "type": "string",
                    "example": "심당빌딩 3층 302호"
                },
                "eid": {
                    "type": "string",
                    "example": "SAMSUNG"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "삼성"
                },
                "orgid": {
                    "type": "integer",
                    "example": 2
                },
                "postno": {
                    "type": "string",
                    "example": "10414"
                },
                "rec": {
                    "type": "string",
                    "example": "비고"
                },
                "reptnm": {
                    "type": "string",
                    "example": "고영호"
                },
                "type": {
                    "type": "integer",
                    "example": 1
                },
                "updatedat": {
                    "type": "string",
                    "example": "2020-01-29 13:10:39"
                },
                "useyn": {
                    "type": "string",
                    "example": "Y"
                }
            }
        },
        "models.FailedMessage": {
            "type": "object",
            "properties": {
                "err": {
                    "type": "object"
                },
                "message": {
                    "type": "string",
                    "example": "failed"
                }
            }
        },
        "models.Message": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "models.Users": {
            "type": "object",
            "properties": {
                "admin": {
                    "type": "integer",
                    "example": 1
                },
                "createdat": {
                    "type": "string",
                    "example": "TIMESTAMP"
                },
                "custid": {
                    "type": "integer",
                    "example": 23
                },
                "dept": {
                    "type": "string",
                    "example": "경영지원팀"
                },
                "email": {
                    "type": "string",
                    "example": "example@example.com"
                },
                "gfid": {
                    "type": "integer",
                    "example": 12
                },
                "id": {
                    "type": "integer",
                    "example": 4
                },
                "name": {
                    "type": "string",
                    "example": "강준구"
                },
                "phone": {
                    "type": "string",
                    "example": "01012341234"
                },
                "position": {
                    "type": "string",
                    "example": "사원"
                },
                "pwd": {
                    "type": "string",
                    "example": "abcd1234"
                },
                "rec": {
                    "type": "string",
                    "example": "비고"
                },
                "updatedat": {
                    "type": "string",
                    "example": "SAMSUNG"
                },
                "useyn": {
                    "type": "string",
                    "example": "Y"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
