definitions:
  controller.Command:
    properties:
      actionkey:
        example: acky
        type: string
      actionval:
        example: 200
        type: integer
      dev-id:
        example: Wxldi39DJecl2dUdlJWL34
        type: string
    required:
    - actionkey
    - actionval
    - dev-id
    type: object
  controller.CommandResponse:
    properties:
      message:
        example: success
        type: string
      subscribeCount:
        example: 5
        type: integer
    type: object
  controller.EquipResponse:
    properties:
      i:
        example: KyvrjRACQJGd3Q7Q9udzo4
        type: string
      k:
        example: co2
        type: string
      value:
        items:
          $ref: '#/definitions/controller.TimeValue'
        type: array
    type: object
  controller.EquipSeries:
    properties:
      i:
        example: KyvrjRACQJGd3Q7Q9udzo4
        type: string
      k:
        example: co2
        type: string
      m:
        example: 302
        type: integer
      t:
        example: "2019-02-02"
        type: string
    type: object
  controller.EventData:
    properties:
      actkey:
        example: acky
        type: string
      actval:
        example: "20"
        type: string
      curval:
        example: 812
        type: integer
      etype:
        example: err
        type: string
      eventkey:
        example: co2
        type: string
      limit:
        example: "50"
        type: string
      model:
        example: "14"
        type: string
      notikey:
        example: "1"
        type: string
      site:
        example: site004
        type: string
      t:
        example: "2019-02-02"
        type: string
    type: object
  controller.ResponseEventData:
    properties:
      eventList:
        items:
          $ref: '#/definitions/controller.EventData'
        type: array
      i:
        example: KyvrjRACQJGd3Q7Q9udzo4
        type: string
    type: object
  controller.SiteLastDataResponse:
    properties:
      SID:
        example: site004
        type: string
      lastData:
        items:
          $ref: '#/definitions/controller.EquipSeries'
        type: array
    type: object
  controller.TimeValue:
    properties:
      m:
        example: 302
        type: integer
      t:
        example: "2019-02-02"
        type: string
    type: object
  mid.login:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  mid.loginSuccess:
    properties:
      code:
        example: "200"
        type: string
      expire:
        example: "2020-02-28T09:15:29+09:00"
        type: string
      token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJDSUQiOjIsIklzQWRtaW4iOnRydWUsIlVJRCI6NDgsIlVzZXJOYW1lIjoi6rmA7ZiV6re8IiwiZXhwIjoxNTgyODQ4OTI5LCJvcmlnX2lhdCI6MTU4MjI0NDEyOX0.ErN3ajVe7Sj5s6jaJQFGfMMaeP8jietm9uP0feacfxA
        type: string
    type: object
  models.Custom:
    properties:
      appryn:
        example: "Y"
        type: string
      basadr:
        example: 서울특별시 강서구 화곡로 12
        type: string
      compno:
        example: "17282718127"
        type: string
      createdat:
        example: "2020-01-29 13:10:39"
        type: string
      dtladr:
        example: 심당빌딩 3층 302호
        type: string
      eid:
        example: SAMSUNG
        type: string
      id:
        example: 1
        type: integer
      name:
        example: 삼성
        type: string
      orgid:
        example: 2
        type: integer
      postno:
        example: "10414"
        type: string
      rec:
        example: 비고
        type: string
      reptnm:
        example: 고영호
        type: string
      type:
        example: 1
        type: integer
      updatedat:
        example: "2020-01-29 13:10:39"
        type: string
      useyn:
        example: "Y"
        type: string
    type: object
  models.Device:
    properties:
      authid:
        example: '?'
        type: string
      authkey:
        example: ??
        type: string
      createdat:
        example: "2020-01-29 13:10:39"
        type: string
      custid:
        example: 4
        type: integer
      equpid:
        example: 1
        type: integer
      firmware:
        example: firmware version
        type: string
      id:
        example: TD2BDhvjKEaZo37c4DLAq6
        type: string
      modelid:
        example: 4
        type: integer
      name:
        example: device-37
        type: string
      prtctype:
        example: prtctype
        type: string
      rec:
        example: 비고
        type: string
      serialno:
        example: 102312-12312
        type: string
      siteid:
        example: 1
        type: integer
      status:
        example: "1"
        type: string
      tag:
        example: tag
        type: string
      type:
        example: ??
        type: string
      updatedat:
        example: "2020-01-29 13:10:39"
        type: string
      useyn:
        example: "Y"
        type: string
    type: object
  models.FailedMessage:
    properties:
      err:
        type: object
      message:
        example: failed
        type: string
    type: object
  models.Model:
    properties:
      createdat:
        example: "2020-01-29 13:10:39"
        type: string
      custid:
        example: 4
        type: integer
      firmware:
        example: firmware version
        type: string
      id:
        example: 4
        type: integer
      name:
        example: viux-38
        type: string
      prtcio:
        example: "1"
        type: string
      prtctype:
        example: prtctype
        type: string
      rec:
        example: 비고
        type: string
      tag:
        example: tag
        type: string
      type:
        example: ??
        type: string
      updatedat:
        example: "2020-01-29 13:10:39"
        type: string
      useyn:
        example: "Y"
        type: string
    type: object
  models.Site:
    properties:
      basadr:
        example: 서울특별시 강서구 화곡로 132
        type: string
      createdat:
        example: "2020-01-29 13:10:39"
        type: string
      custid:
        example: 1
        type: integer
      dtladr:
        example: 심당빌딩 3층 301호
        type: string
      id:
        example: 1
        type: integer
      lat:
        example: 32°
        type: string
      lon:
        example: 24°
        type: string
      name:
        example: 제주1공장
        type: string
      postno:
        example: "10232"
        type: string
      rec:
        example: 비고
        type: string
      type:
        example: ??
        type: string
      updatedat:
        example: "2020-01-29 13:10:39"
        type: string
      useyn:
        example: "Y"
        type: string
    type: object
  models.Users:
    properties:
      admin:
        example: 1
        type: integer
      createdat:
        example: TIMESTAMP
        type: string
      custid:
        example: 23
        type: integer
      dept:
        example: 경영지원팀
        type: string
      email:
        example: example@example.com
        type: string
      gfid:
        example: 12
        type: integer
      id:
        example: 4
        type: integer
      name:
        example: 강준구
        type: string
      phone:
        example: "01012341234"
        type: string
      position:
        example: 사원
        type: string
      pwd:
        example: abcd1234
        type: string
      rec:
        example: 비고
        type: string
      updatedat:
        example: SAMSUNG
        type: string
      useyn:
        example: "Y"
        type: string
    type: object
info:
  contact: {}
  license: {}
paths:
  /auth/device:
    get:
      consumes:
      - application/json
      description: 로그인한 유저 고객사의 모델리스트  Authorization Bearer token 을 넣으세요
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Device'
            type: array
      security:
      - ApiKeyAuth: []
      tags:
      - device
  /auth/device/{id}:
    get:
      consumes:
      - application/json
      description: 모델 단일조회  Authorization Bearer token 을 넣으세요
      parameters:
      - description: 장치아이디
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Device'
      security:
      - ApiKeyAuth: []
      tags:
      - device
  /auth/model:
    get:
      consumes:
      - application/json
      description: 로그인한 유저 고객사의 모델리스트  Authorization Bearer token 을 넣으세요
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Model'
            type: array
      security:
      - ApiKeyAuth: []
      tags:
      - model
  /auth/model/{id}:
    get:
      consumes:
      - application/json
      description: 모델 단일조회  Authorization Bearer token 을 넣으세요
      operationId: get-string-by-int
      parameters:
      - description: 모델아이디
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Model'
      security:
      - ApiKeyAuth: []
      tags:
      - model
  /auth/site:
    get:
      consumes:
      - application/json
      description: 로그인한 유저 고객사의 사이트리스트  Authorization Bearer token 을 넣으세요
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Site'
            type: array
      security:
      - ApiKeyAuth: []
      tags:
      - site
  /auth/site/{id}:
    get:
      consumes:
      - application/json
      operationId: get-string-by-int
      parameters:
      - description: 사이트아이디
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Site'
      security:
      - ApiKeyAuth: []
      tags:
      - site
  /command:
    post:
      consumes:
      - application/json
      description: redis publish
      parameters:
      - description: command
        in: body
        name: command
        required: true
        schema:
          $ref: '#/definitions/controller.Command'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.CommandResponse'
      tags:
      - redis
  /customs:
    get:
      consumes:
      - application/json
      description: 전체고객 목록조회
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Custom'
            type: array
      tags:
      - Custom
  /customs/{id}:
    get:
      consumes:
      - application/json
      description: 고객 id로 고객 단일조회
      operationId: get-string-by-int
      parameters:
      - description: 고객아이디
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Custom'
      summary: '{id}고객아이디'
      tags:
      - Custom
  /equip:
    get:
      consumes:
      - application/json
      description: iotdata5 조회 limit offset 을 넣지않으면 최근 10건
      parameters:
      - description: 장치아이디
        in: query
        name: id
        required: true
        type: string
      - description: 측정키
        in: query
        name: key
        required: true
        type: string
      - description: limit
        in: query
        name: limit
        type: integer
      - description: offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.EquipResponse'
      tags:
      - equip
  /event:
    get:
      consumes:
      - application/json
      description: 장치의 최근이벤트 히스토리 조회
      parameters:
      - description: 장치아이디
        in: query
        name: id
        required: true
        type: string
      - description: limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.ResponseEventData'
      tags:
      - equip
  /login:
    post:
      consumes:
      - application/json
      description: 로그인후 jwt토큰발행
      parameters:
      - description: 아이디 및 패스워드
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/mid.login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/mid.loginSuccess'
      tags:
      - login
  /site:
    get:
      consumes:
      - application/json
      description: 해당사이트에 속한 장치들의 최근측정데이터
      parameters:
      - description: 사이트아이디
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.SiteLastDataResponse'
      tags:
      - equip
  /users:
    get:
      consumes:
      - application/json
      description: 전체사용자 목록조회
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Users'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.FailedMessage'
      tags:
      - User
  /users/{id}:
    get:
      consumes:
      - application/json
      description: 사용자 id로 사용자 단일조회
      operationId: get-string-by-int
      parameters:
      - description: 사용자아이디
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Users'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.FailedMessage'
      summary: '{id} 사용자아이디'
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
